try {
    hello();
} catch (e) {
    console.log(e)
}

try {
    hello();
} catch (e) {
    console.log('This in an error')
}

